// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tt_design_core_d_cpp
arma::mat tt_design_core_d_cpp(const arma::mat& Left, const arma::mat& Right, const arma::mat& Bk);
RcppExport SEXP _TTPsplines_tt_design_core_d_cpp(SEXP LeftSEXP, SEXP RightSEXP, SEXP BkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Left(LeftSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Right(RightSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Bk(BkSEXP);
    rcpp_result_gen = Rcpp::wrap(tt_design_core_d_cpp(Left, Right, Bk));
    return rcpp_result_gen;
END_RCPP
}
// contract_left_step_cpp
arma::mat contract_left_step_cpp(const arma::mat& left, const arma::cube& core, const arma::mat& Bk);
RcppExport SEXP _TTPsplines_contract_left_step_cpp(SEXP leftSEXP, SEXP coreSEXP, SEXP BkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type core(coreSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Bk(BkSEXP);
    rcpp_result_gen = Rcpp::wrap(contract_left_step_cpp(left, core, Bk));
    return rcpp_result_gen;
END_RCPP
}
// contract_right_step_cpp
arma::mat contract_right_step_cpp(const arma::mat& right, const arma::cube& core, const arma::mat& Bk);
RcppExport SEXP _TTPsplines_contract_right_step_cpp(SEXP rightSEXP, SEXP coreSEXP, SEXP BkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type right(rightSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type core(coreSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Bk(BkSEXP);
    rcpp_result_gen = Rcpp::wrap(contract_right_step_cpp(right, core, Bk));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_core_update_cpp
arma::vec gaussian_core_update_cpp(const arma::vec& yc, const arma::mat& Left, const arma::mat& Right, const arma::mat& Bk, const arma::mat& penalty, double lambda);
RcppExport SEXP _TTPsplines_gaussian_core_update_cpp(SEXP ycSEXP, SEXP LeftSEXP, SEXP RightSEXP, SEXP BkSEXP, SEXP penaltySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type yc(ycSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Left(LeftSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Right(RightSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Bk(BkSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_core_update_cpp(yc, Left, Right, Bk, penalty, lambda));
    return rcpp_result_gen;
END_RCPP
}
// tt_contraction_d_cpp
arma::vec tt_contraction_d_cpp(const List& cores_list, const List& basis_list);
RcppExport SEXP _TTPsplines_tt_contraction_d_cpp(SEXP cores_listSEXP, SEXP basis_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type cores_list(cores_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type basis_list(basis_listSEXP);
    rcpp_result_gen = Rcpp::wrap(tt_contraction_d_cpp(cores_list, basis_list));
    return rcpp_result_gen;
END_RCPP
}
// tt_fit_d_cpp
List tt_fit_d_cpp(const arma::vec& y, const List& basis_list, const List& init_cores, const arma::vec& lambda, const List& penalties_list, int sweeps, bool return_jacobian);
RcppExport SEXP _TTPsplines_tt_fit_d_cpp(SEXP ySEXP, SEXP basis_listSEXP, SEXP init_coresSEXP, SEXP lambdaSEXP, SEXP penalties_listSEXP, SEXP sweepsSEXP, SEXP return_jacobianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const List& >::type basis_list(basis_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type init_cores(init_coresSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const List& >::type penalties_list(penalties_listSEXP);
    Rcpp::traits::input_parameter< int >::type sweeps(sweepsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_jacobian(return_jacobianSEXP);
    rcpp_result_gen = Rcpp::wrap(tt_fit_d_cpp(y, basis_list, init_cores, lambda, penalties_list, sweeps, return_jacobian));
    return rcpp_result_gen;
END_RCPP
}
// effective_df_cpp
double effective_df_cpp(const arma::mat& jacobian, const arma::mat& penalty);
RcppExport SEXP _TTPsplines_effective_df_cpp(SEXP jacobianSEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type jacobian(jacobianSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(effective_df_cpp(jacobian, penalty));
    return rcpp_result_gen;
END_RCPP
}
// weighted_core_system_cpp
List weighted_core_system_cpp(const arma::vec& zc, const arma::mat& Left, const arma::mat& Right, const arma::mat& Bk, const arma::vec& weight);
RcppExport SEXP _TTPsplines_weighted_core_system_cpp(SEXP zcSEXP, SEXP LeftSEXP, SEXP RightSEXP, SEXP BkSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type zc(zcSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Left(LeftSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Right(RightSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Bk(BkSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_core_system_cpp(zc, Left, Right, Bk, weight));
    return rcpp_result_gen;
END_RCPP
}
// conditional_gcv_cpp
List conditional_gcv_cpp(const arma::vec& yw, const arma::mat& Xw, const arma::mat& S, const arma::mat& P, const arma::vec& b, double lambda);
RcppExport SEXP _TTPsplines_conditional_gcv_cpp(SEXP ywSEXP, SEXP XwSEXP, SEXP SSEXP, SEXP PSEXP, SEXP bSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type yw(ywSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xw(XwSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(conditional_gcv_cpp(yw, Xw, S, P, b, lambda));
    return rcpp_result_gen;
END_RCPP
}
// optimize_lambda_gcv_cpp
List optimize_lambda_gcv_cpp(const arma::vec& yw, const arma::mat& Xw, const arma::mat& S, const arma::mat& P, const arma::vec& b, double lambda_min, double lambda_max, double tol);
RcppExport SEXP _TTPsplines_optimize_lambda_gcv_cpp(SEXP ywSEXP, SEXP XwSEXP, SEXP SSEXP, SEXP PSEXP, SEXP bSEXP, SEXP lambda_minSEXP, SEXP lambda_maxSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type yw(ywSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xw(XwSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_min(lambda_minSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_lambda_gcv_cpp(yw, Xw, S, P, b, lambda_min, lambda_max, tol));
    return rcpp_result_gen;
END_RCPP
}
// weighted_core_update_cgcv_cpp
List weighted_core_update_cgcv_cpp(const arma::vec& zc, const arma::mat& Left, const arma::mat& Right, const arma::mat& Bk, const arma::vec& weight, const arma::mat& penalty, double lambda, std::string criterion, double lambda_min, double lambda_max, double tol);
RcppExport SEXP _TTPsplines_weighted_core_update_cgcv_cpp(SEXP zcSEXP, SEXP LeftSEXP, SEXP RightSEXP, SEXP BkSEXP, SEXP weightSEXP, SEXP penaltySEXP, SEXP lambdaSEXP, SEXP criterionSEXP, SEXP lambda_minSEXP, SEXP lambda_maxSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type zc(zcSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Left(LeftSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Right(RightSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Bk(BkSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< std::string >::type criterion(criterionSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_min(lambda_minSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_core_update_cgcv_cpp(zc, Left, Right, Bk, weight, penalty, lambda, criterion, lambda_min, lambda_max, tol));
    return rcpp_result_gen;
END_RCPP
}
// tt_cgcv_fit_cpp
List tt_cgcv_fit_cpp(const arma::vec& y, const List& basis_list, const List& init_cores, const List& penalties_list, arma::vec lambda_init, int sweeps, double lambda_min, double lambda_max, double tol, double tol_lambda, bool return_jacobian);
RcppExport SEXP _TTPsplines_tt_cgcv_fit_cpp(SEXP ySEXP, SEXP basis_listSEXP, SEXP init_coresSEXP, SEXP penalties_listSEXP, SEXP lambda_initSEXP, SEXP sweepsSEXP, SEXP lambda_minSEXP, SEXP lambda_maxSEXP, SEXP tolSEXP, SEXP tol_lambdaSEXP, SEXP return_jacobianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const List& >::type basis_list(basis_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type init_cores(init_coresSEXP);
    Rcpp::traits::input_parameter< const List& >::type penalties_list(penalties_listSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< int >::type sweeps(sweepsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_min(lambda_minSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type tol_lambda(tol_lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type return_jacobian(return_jacobianSEXP);
    rcpp_result_gen = Rcpp::wrap(tt_cgcv_fit_cpp(y, basis_list, init_cores, penalties_list, lambda_init, sweeps, lambda_min, lambda_max, tol, tol_lambda, return_jacobian));
    return rcpp_result_gen;
END_RCPP
}
// tt_glm_pirls_cgcv_cpp
List tt_glm_pirls_cgcv_cpp(const arma::vec& y, const List& basis_list, const List& init_cores, const List& penalties_list, std::string family, arma::vec lambda_init, int pirls_iter, int als_sweeps, double lambda_min, double lambda_max, double tol, double tol_dev, bool select_lambda);
RcppExport SEXP _TTPsplines_tt_glm_pirls_cgcv_cpp(SEXP ySEXP, SEXP basis_listSEXP, SEXP init_coresSEXP, SEXP penalties_listSEXP, SEXP familySEXP, SEXP lambda_initSEXP, SEXP pirls_iterSEXP, SEXP als_sweepsSEXP, SEXP lambda_minSEXP, SEXP lambda_maxSEXP, SEXP tolSEXP, SEXP tol_devSEXP, SEXP select_lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const List& >::type basis_list(basis_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type init_cores(init_coresSEXP);
    Rcpp::traits::input_parameter< const List& >::type penalties_list(penalties_listSEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< int >::type pirls_iter(pirls_iterSEXP);
    Rcpp::traits::input_parameter< int >::type als_sweeps(als_sweepsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_min(lambda_minSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type tol_dev(tol_devSEXP);
    Rcpp::traits::input_parameter< bool >::type select_lambda(select_lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(tt_glm_pirls_cgcv_cpp(y, basis_list, init_cores, penalties_list, family, lambda_init, pirls_iter, als_sweeps, lambda_min, lambda_max, tol, tol_dev, select_lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TTPsplines_tt_design_core_d_cpp", (DL_FUNC) &_TTPsplines_tt_design_core_d_cpp, 3},
    {"_TTPsplines_contract_left_step_cpp", (DL_FUNC) &_TTPsplines_contract_left_step_cpp, 3},
    {"_TTPsplines_contract_right_step_cpp", (DL_FUNC) &_TTPsplines_contract_right_step_cpp, 3},
    {"_TTPsplines_gaussian_core_update_cpp", (DL_FUNC) &_TTPsplines_gaussian_core_update_cpp, 6},
    {"_TTPsplines_tt_contraction_d_cpp", (DL_FUNC) &_TTPsplines_tt_contraction_d_cpp, 2},
    {"_TTPsplines_tt_fit_d_cpp", (DL_FUNC) &_TTPsplines_tt_fit_d_cpp, 7},
    {"_TTPsplines_effective_df_cpp", (DL_FUNC) &_TTPsplines_effective_df_cpp, 2},
    {"_TTPsplines_weighted_core_system_cpp", (DL_FUNC) &_TTPsplines_weighted_core_system_cpp, 5},
    {"_TTPsplines_conditional_gcv_cpp", (DL_FUNC) &_TTPsplines_conditional_gcv_cpp, 6},
    {"_TTPsplines_optimize_lambda_gcv_cpp", (DL_FUNC) &_TTPsplines_optimize_lambda_gcv_cpp, 8},
    {"_TTPsplines_weighted_core_update_cgcv_cpp", (DL_FUNC) &_TTPsplines_weighted_core_update_cgcv_cpp, 11},
    {"_TTPsplines_tt_cgcv_fit_cpp", (DL_FUNC) &_TTPsplines_tt_cgcv_fit_cpp, 11},
    {"_TTPsplines_tt_glm_pirls_cgcv_cpp", (DL_FUNC) &_TTPsplines_tt_glm_pirls_cgcv_cpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_TTPsplines(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
