# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tt_design_core_d_cpp <- function(Left, Right, Bk) {
    .Call(`_TTPsplines_tt_design_core_d_cpp`, Left, Right, Bk)
}

contract_left_step_cpp <- function(left, core, Bk) {
    .Call(`_TTPsplines_contract_left_step_cpp`, left, core, Bk)
}

contract_right_step_cpp <- function(right, core, Bk) {
    .Call(`_TTPsplines_contract_right_step_cpp`, right, core, Bk)
}

gaussian_core_update_cpp <- function(yc, Left, Right, Bk, penalty, lambda) {
    .Call(`_TTPsplines_gaussian_core_update_cpp`, yc, Left, Right, Bk, penalty, lambda)
}

tt_contraction_d_cpp <- function(cores_list, basis_list) {
    .Call(`_TTPsplines_tt_contraction_d_cpp`, cores_list, basis_list)
}

#' Full TT-ALS fit (Gaussian, fixed anisotropic λ).
#' Returns cores, mu, optional jacobian, block sizes.
tt_fit_d_cpp <- function(y, basis_list, init_cores, lambda, penalties_list, sweeps, return_jacobian = TRUE) {
    .Call(`_TTPsplines_tt_fit_d_cpp`, y, basis_list, init_cores, lambda, penalties_list, sweeps, return_jacobian)
}

#' Effective DF: tr[(J'J + P)^{-1} J'J]
effective_df_cpp <- function(jacobian, penalty) {
    .Call(`_TTPsplines_effective_df_cpp`, jacobian, penalty)
}

#' Build weighted Gram S=X'WX and RHS b=X'W zc (materializes X).
weighted_core_system_cpp <- function(zc, Left, Right, Bk, weight) {
    .Call(`_TTPsplines_weighted_core_system_cpp`, zc, Left, Right, Bk, weight)
}

#' Conditional GCV value / coef for fixed λ (weighted or unweighted via Xw,yw).
conditional_gcv_cpp <- function(yw, Xw, S, P, b, lambda) {
    .Call(`_TTPsplines_conditional_gcv_cpp`, yw, Xw, S, P, b, lambda)
}

#' Brent/golden optimize λ on conditional GCV (log scale).
optimize_lambda_gcv_cpp <- function(yw, Xw, S, P, b, lambda_min = 1e-2, lambda_max = 1e2, tol = 1e-3) {
    .Call(`_TTPsplines_optimize_lambda_gcv_cpp`, yw, Xw, S, P, b, lambda_min, lambda_max, tol)
}

#' Weighted core update with optional cGCV λ (criterion: "fixed" | "gcv").
weighted_core_update_cgcv_cpp <- function(zc, Left, Right, Bk, weight, penalty, lambda, criterion = "gcv", lambda_min = 1e-2, lambda_max = 1e2, tol = 1e-3) {
    .Call(`_TTPsplines_weighted_core_update_cgcv_cpp`, zc, Left, Right, Bk, weight, penalty, lambda, criterion, lambda_min, lambda_max, tol)
}

#' Gaussian TT-ALS with per-core conditional GCV (Rcpp).
tt_cgcv_fit_cpp <- function(y, basis_list, init_cores, penalties_list, lambda_init, sweeps = 12L, lambda_min = 1e-2, lambda_max = 1e2, tol = 1e-3, tol_lambda = 1e-3, return_jacobian = FALSE) {
    .Call(`_TTPsplines_tt_cgcv_fit_cpp`, y, basis_list, init_cores, penalties_list, lambda_init, sweeps, lambda_min, lambda_max, tol, tol_lambda, return_jacobian)
}

#' GLM PIRLS + weighted TT-ALS with per-core conditional GCV (Rcpp).
#' family: "bernoulli" | "poisson" (gaussian → use tt_cgcv_fit_cpp).
tt_glm_pirls_cgcv_cpp <- function(y, basis_list, init_cores, penalties_list, family, lambda_init, pirls_iter = 12L, als_sweeps = 4L, lambda_min = 1e-2, lambda_max = 1e2, tol = 1e-3, tol_dev = 1e-6, select_lambda = TRUE) {
    .Call(`_TTPsplines_tt_glm_pirls_cgcv_cpp`, y, basis_list, init_cores, penalties_list, family, lambda_init, pirls_iter, als_sweeps, lambda_min, lambda_max, tol, tol_dev, select_lambda)
}

